# Generated by Django 2.2.16 on 2022-07-21 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220721_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Username должен содержать только буквы, цифры и символы: '@', '.', '+', '-', '_'", regex='^(?!temp)^[\\w.@+-]+$')]),
        ),
    ]
