# Generated by Django 2.2.16 on 2022-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220721_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'аутентифицированный пользоветель'), ('moderator', 'модератор'), ('admin', 'администратор')], default='user', max_length=10, verbose_name='role'),
        ),
    ]
